name: news_api
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

assets:
  - .env

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  args: ^2.0.0
  http: ^0.13.5
  logger: ^1.1.0
  mockito: ^5.3.2
  redis_dart: ^0.1.0+4
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  test: ^1.22.0

dev_dependencies:
  lints: ^2.0.0
